services:
  - type: web
    name: flask-react-app
    env: python
    rootDirectory: .
    buildCommand: |
      pip install -r requirements.txt
    startCommand: |
      cd /opt/render/project/src && gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.10